name: catharsis_cards
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+36

environment:
  sdk: ">=3.7.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # UI & Animation
  auto_size_text: 3.0.0
  flutter_animate: ^4.5.2
  flutter_card_swiper: ^7.0.2
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  page_transition: ^2.2.1
  google_fonts: ^6.2.1
  
  # Navigation & Routing
  go_router: ^16.0.0
  
  # Network & Caching
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  flutter_cache_manager: 3.4.1
  http: ^1.1.0
  
  # Data & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: any
  sqflite_common: any
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_analytics: any
  firebase_storage: ^12.4.10
  cloud_firestore: any
  cloud_functions: ^5.1.4
  
  

  # Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1

  
  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9
  
  # File System
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: ^2.3.0
  
  # URL & External
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  
  # Utilities
  intl: ^0.20.2
  json_path: ^0.7.6
  timeago: ^3.7.1
  csv: ^6.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  timezone: ^0.10.1
  share_plus: ^11.0.0
  permission_handler: ^12.0.1
  google_mobile_ads: ^5.0.0 
  crypto: ^3.0.3   
  
  # Icons
  cupertino_icons: ^1.0.8

  # Purchasing & Payments 
  in_app_purchase: ^3.0.8
  in_app_purchase_storekit: ^0.4.3
  profanity_filter: ^2.0.0
  awesome_notifications: ^0.10.1
  device_preview: ^1.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpeg"
  remove_alpha_ios: true
  adaptive_icon_background: "#fae8c2"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  
  fonts:
    - family: Runtime
      fonts:
        - asset: assets/fonts/Runtime.otf
  
  assets:
    - assets/images/heart_icon.png
    - assets/images/home_icon.png
    - assets/images/profile_icon.png
    - assets/images/settings_icon.png
    - assets/images/share_icon.png
    - assets/images/preferences_icon.png
    - assets/images/background_texture.png
    - assets/Card_Statements_Questions.csv
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
    - assets/images/avatar5.png
    - assets/images/avatar6.png
    - assets/images/default_avatar.jpeg
    - assets/images/catharsis_word_only.png
    - assets/images/dark_mode_background.png
    - assets/images/light_mode_background.png
    - assets/images/default_mode_background.png
    - assets/images/dark_mode_stat_card.png
    - assets/images/light_mode_stat_card.png
    - assets/images/change_theme_icon.png
    - assets/images/saved_icon.png
    - assets/images/logout_icon.png
    - assets/images/dark_theme_image.png
    - assets/images/light_theme_image.png
    - assets/images/default_theme_image.png
    - assets/images/boat_illustration.png
    - assets/images/spirituality_icon.png
    - assets/images/society_icon.png
    - assets/images/interactions_relationships_icon.png
    - assets/images/personal_development_icon.png
    - assets/images/love_intimacy_icon.png
    - assets/images/light_mode_preference_menu.png
    - assets/images/app_icon_foreground.png
    - .env
